### PR TITLE
ubus: add explicit support for deferring incoming requests

### PR DESCRIPTION
**Pull request by nbd168**
This is needed when asynchronously processing requests via uloop, e.g. using uclient.

### CODE REVIEW

**Comment by jow-** [comment]
Can you try to add a short ucode usage example to the commit message itself?

So to understand the intent correctly: you want to be able to return from the callback without the request context being replied to, instead you want to stow away the context somewhere and invoke its .reply() later from another scope, e.g. within some timer or io callback?

**Comment by nbd168** [comment]
Correct. I added the example that I was testing with.

**Comment by nbd168** [comment]
I'm planning on using this in combination with the uclient module that I wrote in order to build a hostapd 'afcd' replacement for 6 GHz frequency coordination (required by FCC for 6 GHz standard power levels).

**Comment by jow-** [comment]
Merged, thanks!

**Pull request merged**
